dir: ".bash.d"
links:
  - ".inputrc"
  - "bash.d/*:.bash.d"
lines:
  - path: ".bashrc"
    line: "[[ -n \"$PS1\" ]] && [[ -f ~/.bash_profile ]] && source ~/.bash_profile"
  - path: ".bash_profile"
    line: "[[ -f ~/.bash.d/init.bash ]] && source ~/.bash.d/init.bash"
