---
role:
  pkg:
    - bash
    - bash-completion
    # - curl
    - tree
    - name: fzf
      os: ["darwin"]
    # - gzip
    - name: unrar # non-free
      os: ["!debian"]
      # os: ["arch", "darwin"]
    - unzip
    # - wget
  # pkg_android: # termux
  #   - busybox
  #   - ca-certificates
  #   - coreutils
  #   - curl
  #   - grep
  #   - less
  #   - man
  #   - ncurses-utils
  #   - readline
  link:
    - ".inputrc"
    - "bin/*:bin"
    - "*.bash:.bash.d"
    - "aliases:.bash.d"
    - "environment:.bash.d"
    - "functions:.bash.d"
    - "plugins:.bash.d"
  line: # FIXME: check if ~/.bashrc is already sourced from ~/.bash_profile
    ".bashrc": "[[ -n \"$PS1\" ]] && [[ -f ~/.bash_profile ]] && source ~/.bash_profile"
    ".bash_profile": "[[ -f ~/.bash.d/init.bash ]] && source ~/.bash.d/init.bash"
  post_install:
    # Quickfix arch default ~/.bash_profile
    - "if test -f ~/.bash_profile; then sed -i '/[[ -f ~\\/.bashrc ]] && . ~\\/.bashrc/d' ~/.bash_profile; fi"
